// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import ReactController from "./react_controller";
application.register("react", ReactController);

import LoginController from "./login_controller";
application.register("login", LoginController);

import SignUpController from "./sign_up_controller";
application.register("sign_up", SignUpController);
